[package]
name = "eagle_dev_test"
version = "0.1.0"
authors = ["James Cox-Morton <th3james@fastmail.fm>"]

[dependencies]
hyper = { version = "0.9", default-features = false, features = ["security-framework"] }
rustc-serialize = "*"
